[project]
name = "eigenpy"
version = "2.7.14"
description = "Bindings between Numpy and Eigen using Boost.Python"
readme = "README.md"
license= "BSD-2-Clause"
dependencies = ["cmeel-boost"]
requires-python = ">= 3.8"

[project.urls]
homepage = "https://github.com/stack-of-tasks/eigenpy"

[build-system]
requires = ["cmeel[build]", "numpy", "cmeel-eigen", "cmeel-boost"]
build-backend = "cmeel.build"
