name: Test Wheel packaging

on: ["push", "pull_request"]

jobs:
  build:
    name: "Build python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-10.15"]
        python: ["3.7", "3.10"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
      - name: build cmeel wheel
        run: python -m pip wheel -w wh .
        env:
          CMEEL_JOBS: 1
          CMEEL_TEST_JOBS: 1
          CMEEL_LOG_LEVEL: DEBUG
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  test:
    needs: ["build"]
    name: "Test python ${{ matrix.python }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"
    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        python: ["3.7", "3.10"]
    steps:
      - uses: actions/download-artifact@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: setup
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel simple503
          python -m simple503 --sort --base-url "${{ github.workspace }}/artifact" artifact
      - name: install wheel
        run: python -m pip install -i "file://${{ github.workspace }}/artifact" eigenpy
      - name: test
        run: python -c "import eigenpy; assert abs(eigenpy.Quaternion(1, 2, 3, 4).norm() - 5.47722557505) < 1e-7"
        env:
          PYTHONWARNINGS: error
